#!/bin/bash
#nms'
echo "fjsafjdfjfdjfkdjkfj;fjkdjfkaj"
test()
{
	echo "hello world"
}

:<<EOF
echo eof
echo nmyy
echo nmyy
EOF
:<<!
echo gantanhao
echo nmyy
echo nmyy
!
:<<'

echo danin
echo nmyy
echo nmyy
'

